version: '3'

services:
  server:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./source:/var/www/html"
    #ports:
    #  - "80:80"
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - "./source:/var/www/html"
